Egui integration
BVE-Reborn/rend3 pull request #230
Opened 2021-10-10 16:12 UTC by MindSwipe

## Checklist
- [x] cargo clippy reports no issues
- [x] cargo deny issues have been fixed or added to deny.toml
- [x] relevant examples/test cases run
- [x] changes added to changelog
  - [x] Add credit to yourself for each change: `Added new functionality @githubname`.

## Problems PR Solves
This pull request creates an initial egui integration, so users can use rend3 to draw an immediate mode GUI

## Related Issues
#192, or at least half (i.e the egui part)

2021-10-11 21:08 UTC, cwfitzgerald requested changes
Some minor things, but looking really good!

2021-10-11 21:08 UTC, cwfitzgerald commented on rend3-egui/Cargo.toml
> +egui = "0.14.2"
These should only be `0.14` as that's all we really require.

2021-10-11 21:08 UTC, cwfitzgerald commented on rend3-egui/Cargo.toml
> +egui_wgpu_backend = { git = "https://github.com/hasenbanck/egui_wgpu_backend.git", rev = "6f1f59be1054a523cd28e3ba020b3c7490793e9a" }
We should be able to use 0.13 now.

2021-10-11 21:08 UTC, cwfitzgerald commented on rend3-egui/Cargo.toml
> +[dependencies]
nit: sort alphabetically

2021-10-11 21:08 UTC, cwfitzgerald commented on rend3-egui/Cargo.toml
> +authors = ["Juri Furer <juri.furer@protonmail.com>"]
This should be `The rend3 Developers` now

2021-10-11 21:08 UTC, cwfitzgerald commented on rend3-egui/src/lib.rs
> +        // });
Dead code.

2021-10-11 21:08 UTC, cwfitzgerald commented on examples/egui/src/main.rs
> +                // let _stats = renderer.render(&mut egui_routine, &input, frame.as_view());
Dead code

2021-10-11 21:08 UTC, cwfitzgerald commented on examples/egui/src/main.rs
> +    )));
We don't need any of these in Arc<Mutex<T>> as we don't use multiple threads in this example. scene-viewer only needs it because it does async loading.

2021-10-11 21:08 UTC, cwfitzgerald commented on examples/egui/src/main.rs
> +
Missing a call to `renderer.set_aspect_ratio`. If you resize the window it gets all funky looking :)

2021-10-12 09:49 UTC, MindSwipe commented on rend3-egui/Cargo.toml
> +egui = "0.14.2"
Fair enough, updated the dependecies

2021-10-12 09:49 UTC, MindSwipe commented on rend3-egui/Cargo.toml
> +egui_wgpu_backend = { git = "https://github.com/hasenbanck/egui_wgpu_backend.git", rev = "6f1f59be1054a523cd28e3ba020b3c7490793e9a" }
Yup, didn't see it released, updated

2021-10-12 09:49 UTC, MindSwipe commented on rend3-egui/Cargo.toml
> +[dependencies]
Done

2021-10-12 09:50 UTC, MindSwipe commented on rend3-egui/Cargo.toml
> +authors = ["Juri Furer <juri.furer@protonmail.com>"]
Done

2021-10-12 09:50 UTC, MindSwipe commented on rend3-egui/src/lib.rs
> +        // });
Removed

2021-10-12 09:50 UTC, MindSwipe commented on examples/egui/src/main.rs
> +                // let _stats = renderer.render(&mut egui_routine, &input, frame.as_view());
Removed

2021-10-12 09:51 UTC, MindSwipe commented on examples/egui/src/main.rs
> +    )));
I was confused about that when I looked at the scene-viewer example, that's what I get for being sleep deprived. Removed

2021-10-12 09:52 UTC, MindSwipe commented on examples/egui/src/main.rs
> +
Yup, missed that in testing because locally I get a *ton* of errors in the terminal, to the point where the program almost crashes, so I just don't resize the Window
Added it

2021-10-12 15:15 UTC, cwfitzgerald approved these changes
Lookin good!

2021-10-12 15:15 UTC, merged