Allow customizing primitive topology in forward pipeline
BVE-Reborn/rend3 pull request #373
Opened 2022-02-27 10:17 UTC by setzer22

## Checklist

- CI Checked:
  - [ ] `cargo fmt` has been ran
  - [ ] `cargo clippy` reports no issues
  - [ ] `cargo test` succeeds
  - [ ] `cargo rend3-doc` has no warnings
  - [ ] `cargo deny check` issues have been fixed or added to deny.toml
- Manually Checked:
  - [ ] relevant examples/test cases run
  - [ ] changes added to changelog
    - [ ] Add credit to yourself for each change: `Added new functionality @githubname`.

## Related Issues
None that I'm aware

## Description
Here's a very minor change allowing customization of the PrimitiveTopology when building a forward pipeline. This allows reusing the forward pipeline for more things, like a wireframe renderer.

2022-02-28 18:23 UTC, cwfitzgerald requested changes

2022-02-28 18:23 UTC, cwfitzgerald commented on rend3-routine/src/forward.rs
> +        primitive_topology: Option<wgpu::PrimitiveTopology>,
Lets just pass this directly through as `wgpu::PrimitiveTopology`; it has less magic than "none == triangle list".

nit: label should always be last

2022-03-01 10:13 UTC, setzer22 commented
Took care of the comments :+1:  Let me know if there's anything else :smile:

2022-03-01 12:17 UTC, cwfitzgerald approved these changes
Thanks!

2022-03-01 12:17 UTC, merged