update to winit 0.29.4
BVE-Reborn/rend3 pull request #544
Opened 2023-12-19 12:52 UTC by pillowtrucker

## Checklist

- CI Checked:
  - [ √] `cargo fmt` has been ran
  - [√] `cargo clippy` reports no issues
  - [ √] `cargo test` succeeds
  - [ √] `cargo rend3-doc` has no warnings
  - [ ] `cargo deny check` issues have been fixed or added to deny.toml
 
 ```
  error[duplicate]: found 3 duplicate entries for crate 'windows_x86_64_msvc'
    ┌─ /home/wrath/BRAINWORMS-depends/rend3/Cargo.lock:395:1
    │  
395 │ ╭ windows_x86_64_msvc 0.42.2 registry+https://github.com/rust-lang/crates.io-index
396 │ │ windows_x86_64_msvc 0.48.5 registry+https://github.com/rust-lang/crates.io-index
397 │ │ windows_x86_64_msvc 0.52.0 registry+https://github.com/rust-lang/crates.io-index
    │ ╰────────────────────────────────────────────────────────────────────────────────^ lock entries
```
I don't know how to fix that or understand why that's a problem.
- Manually Checked:
  - [√ ] relevant examples/test cases run
  All the examples other than https://github.com/BVE-Reborn/rend3/issues/543
  - [ √] changes added to changelog
    - [ √] Add credit to yourself for each change: `Added new functionality @githubname`.

## Related Issues

## Description
Updated this to winit 0.29.4 since egui ran the update yesterday and dependabot is pestering me

2023-12-19 14:39 UTC, pillowtrucker commented
After fixing up wasm build (noticed on my own branch ci..) Clippy now seems to be demanding the impossible, or at least I'm not sure how to resolve it because the preprocessor blocks are too smart for me and won't let me stick a cheeky return statement or any other hack that I could think of in there based on target arch
```
warning: this let-binding has unit value
   --> rend3-framework/src/lib.rs:306:5
    |
306 | /     let _ = winit_run(event_loop, move |event, event_loop_window_target| {
307 | |         let event = match event {
308 | |             Event::UserEvent(UserResizeEvent::Resize { size, window_id }) => Event::WindowEvent {
309 | |                 window_id,
...   |
363 | |         )
364 | |     });
    | |_______^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#let_unit_value
    = note: `#[warn(clippy::let_unit_value)]` on by default
help: omit the `let` binding
```
If I omit the let binding it will fail on the non-wasm build demanding that I do something with the Result<>

2023-12-20 20:39 UTC, cwfitzgerald commented
Take a look at https://github.com/gfx-rs/wgpu/blob/trunk/examples/src/framework.rs#L378-L390 where I solved that problem in the wgpu exampels

2023-12-31 04:15 UTC, cwfitzgerald requested changes
I have some comments, but I'm just going to address them myself. Looks good in general though, thank you!

2023-12-31 04:15 UTC, cwfitzgerald commented on examples/cube-no-framework/src/main.rs
> +            winit::event::Event::AboutToWait => {
We should use redraw requested for this event

2023-12-31 04:15 UTC, cwfitzgerald commented on rend3-framework/src/lib.rs
> +        exit(1)
Can't this just be an unwrap?

2023-12-31 06:53 UTC, cwfitzgerald approved these changes

2023-12-31 06:53 UTC, merged