Make unlit path sample textures with nearest filtering
BVE-Reborn/rend3 pull request #86
Opened 2021-02-04 00:13 UTC by Noxime

2021-02-05 06:14 UTC, cwfitzgerald requested changes
Code looks fine, just a change of heart in the shader

2021-02-05 06:14 UTC, cwfitzgerald commented on rend3/shaders/lighting/pixel.glsl
> +            if (MATERIAL_FLAG(FLAGS_UNLIT)) {
On second thought we should just have a new material flag that determines which of the two samplers to use.

2021-02-17 00:25 UTC, cwfitzgerald commented
Bump on this?

2021-02-17 19:25 UTC, Noxime commented
Oh sorry, I haven't worked at all on this, I've been busy with other stuff, and probably won't get around to this for next few days either. You are free to implement this yourself if you have time :)

2021-02-17 22:32 UTC, cwfitzgerald commented
No rush at all, just wanted to make sure you didn't forget :)

2021-02-21 22:13 UTC, cwfitzgerald approved these changes
Thanks so much!

2021-02-21 22:13 UTC, merged